packages:
  - app
  - contracts
  - generator

overrides:
  axios@<0.30.0: '>=0.30.0'
  axios@>=0.8.1 <0.28.0: '>=0.28.0'
  next@>=15.0.0 <=15.4.4: '>=15.4.5'
  next@>=15.0.0-canary.0 <15.4.7: '>=15.4.7'
  tmp@<=0.2.3: '>=0.2.4'
