[build]
buildCommand = "pnpm install && pnpm --filter generator build && pnpm --filter app build"
startCommand = "pnpm --filter app start"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "always" 