[build]
buildCommand = "pnpm --filter generator build && pnpm --filter app build"

[start]
cmd = "cd app && echo \"Railway PORT: $PORT\" && echo \"All env vars:\" && env | grep -E \"(PORT|HOST)\" && PORT=$PORT node .next/standalone/app/server.js"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "always" 