[profile.default]
# update solc values if needed for compatability with older contracts
auto_detect_solc = false
solc = '0.8.20'
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    'forge-std/=lib/forge-std/src',
    'solady/=lib/solady/src/',
    'solady-test/=lib/solady/test/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/',
    'openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
]
# ensure that block number + timestamp are realistic when running tests
block_number = 17722462
block_timestamp = 1689711647

# don't pollute bytecode with metadata
bytecode_hash = 'none'
cbor_metadata = false
# grant access to read via_ir-out by default, if necessary
fs_permissions = [
    { access = "read", path = "./via_ir-out" },
    { access = "read", path = "./base64" }
]
# etherscan currently does not support contracts with more than 10 million optimizer runs;
# bytecode is typically unaffected past ~1 million runs anyway
optimizer_runs = 99_999_999

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${ETHEREUM_RPC_URL}"
base = "${BASE_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"

[etherscan]
ethereum = { key = "${ETHERSCAN_API_KEY}"}
base = { key = "${BASESCAN_API_KEY}"}
base_sepolia = { key = "${BASESCAN_API_KEY}"}

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
