# @todo: add mini-app tests
name: Run Tests

on:
  push:
    branches: [master]
    tags: ['*']
  pull_request:
    types: [opened, reopened, synchronize]

env:
  FOUNDRY_PROFILE: ci

permissions:
  contents: write

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          submodules: recursive

      - name: Ensure submodules are up to date
        run: git submodule update --init --recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Forge dependencies
        run: |
          echo "Installing forge-std explicitly..."
          forge install foundry-rs/forge-std --no-git
          echo "Verifying installation..."
          ls -la lib/forge-std/src/Script.sol || echo "Script.sol not found"
        working-directory: contracts

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build
        continue-on-error: true
        working-directory: contracts

      - name: Run Forge tests
        run: |
          FOUNDRY_PROFILE=CI forge test -vvv
        id: test
        working-directory: contracts
